name: Push to chocolatey

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Remove .git folder
        run: rm .git -Force -Recurse
      - name: Remove .github folder
        run: rm .github -Force -Recurse
      - name: Remove README.md
        run: rm README.md
      - name: Install chocolatey
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - name: Authenticate
        run: choco apikey --key ${{ secrets.chocoApiKey }} --source https://push.chocolatey.org/
      - name: Build
        run: choco pack
      - name: Push
        run: choco push --source https://push.chocolatey.org/
